{"name": "test_otp_verification_with_invalid_otp", "status": "passed", "steps": [{"name": "THis test verifies that OTP can't be validated with invalid code", "status": "passed", "start": 1648801626621, "stop": 1648801627132}], "start": 1648801626620, "stop": 1648801627132, "uuid": "49eb4b82-145c-4438-a8e6-6d0cf9a8798c", "historyId": "9c05cad699f92058f0d2843b7c5a1d47", "testCaseId": "d2b3c2b5af37dee5291eb52a968eb4d5", "fullName": "tests.api_testcases.verify_otp.verify_otp_test.TestVerifyEmail#test_otp_verification_with_invalid_otp", "labels": [{"name": "parentSuite", "value": "tests.api_testcases.verify_otp"}, {"name": "suite", "value": "verify_otp_test"}, {"name": "subSuite", "value": "TestVerifyEmail"}, {"name": "host", "value": "pop-os"}, {"name": "thread", "value": "118790-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.api_testcases.verify_otp.verify_otp_test"}]}